// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	structures "github.com/jiraconnector/internal/structures"
	mock "github.com/stretchr/testify/mock"
)

// JiraConnectorInterface is an autogenerated mock type for the JiraConnectorInterface type
type JiraConnectorInterface struct {
	mock.Mock
}

// GetAllProjects provides a mock function with no fields
func (_m *JiraConnectorInterface) GetAllProjects() ([]structures.JiraProject, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllProjects")
	}

	var r0 []structures.JiraProject
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]structures.JiraProject, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []structures.JiraProject); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]structures.JiraProject)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectIssues provides a mock function with given fields: projectId
func (_m *JiraConnectorInterface) GetProjectIssues(projectId string) ([]structures.JiraIssue, error) {
	ret := _m.Called(projectId)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectIssues")
	}

	var r0 []structures.JiraIssue
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]structures.JiraIssue, error)); ok {
		return rf(projectId)
	}
	if rf, ok := ret.Get(0).(func(string) []structures.JiraIssue); ok {
		r0 = rf(projectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]structures.JiraIssue)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectsPage provides a mock function with given fields: search, limit, page
func (_m *JiraConnectorInterface) GetProjectsPage(search string, limit int, page int) (*structures.ResponseProject, error) {
	ret := _m.Called(search, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectsPage")
	}

	var r0 *structures.ResponseProject
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) (*structures.ResponseProject, error)); ok {
		return rf(search, limit, page)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) *structures.ResponseProject); ok {
		r0 = rf(search, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*structures.ResponseProject)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(search, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJiraConnectorInterface creates a new instance of JiraConnectorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJiraConnectorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *JiraConnectorInterface {
	mock := &JiraConnectorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
